### ISSUE TITLE
Some layers from the European Wide Data Package are missing

### ISSUE THREAD

**Issue by therter** [clarity-h2020/data-package#69]
The following hazard characterization layers from the European Wide Data Package are missing (not only on the new geoserver, but also on the old geoserver):
- The layers for the snow days. Examples:
  - europe:PI_snow-days_rcp85_20410101-20701231_ensmean [old link](https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_snow-days_rcp85_20410101-20701231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619), [new link](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_snow-days_rcp85_20410101-20701231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619)
  - europe:PI_snow-days_rcp85_20410101-20701231_ensstd [old link](https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_snow-days_rcp85_20410101-20701231_ensstd&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&tileSize=1536&attribution=&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619),  [new link](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_snow-days_rcp85_20410101-20701231_ensstd&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&tileSize=1536&attribution=&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619) 

- some layers for hot-days-75p. Examples:
  - europe:CI_Tn10p_rcp85_20410101-20701231_ensmean [old link](https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3ACI_Tn10p_rcp85_20410101-20701231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619), [new link](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3ACI_Tn10p_rcp85_20410101-20701231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619)
  - europe:CI_Tn10p_rcp85_20410101-20701231_ensstd [old link](https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3ACI_Tn10p_rcp85_20410101-20701231_ensstd&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619), [new link](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3ACI_Tn10p_rcp85_20410101-20701231_ensstd&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619)
  - europe:HI_Tx75p_rcp85_20410101-20701231_ensmean [old link](https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3AHI_Tx75p_rcp85_20410101-20701231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619), [new link](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3AHI_Tx75p_rcp85_20410101-20701231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619)
  - europe:HI_Tx75p_rcp85_20410101-20701231_ensstd [old link](https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3AHI_Tx75p_rcp85_20410101-20701231_ensstd&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619), [new link](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3AHI_Tx75p_rcp85_20410101-20701231_ensstd&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619)

**Comment by RobAndGo** [comment]
Oh man, again! ![gaah](https://user-images.githubusercontent.com/45385637/83905723-72a0dd00-a762-11ea-86e2-9f0bcab0bcef.gif)

I'll have to look at this in more detail, but I think one of the problems with snow days, was that it was one of the last datasets to be uploaded, and I'm not sure if @ghilbrae or @LauraMTG had time to convert them to geotiff on the Meteogrid server. Indeed, I cannot find it here: https://clarity.meteogrid.com/geoserver/web/


For the index **CI_Tn10p***, I think the problem is that in the geoserver, the index is written with a small "t" instead of with a capital T, i.e. see second line of the long link "....CI_tn10p_...:" :

`https://clarity.meteogrid.com/geoserver/europe/wms?service=WMS&version=1.1.0&request=GetMap&layers=europe%3ACI_tn10p_rcp26_20410101-20701231_ensmean&bbox=2145642.726143716%2C982955.8095900388%2C6605432.868301096%2C5706496.981659953&width=725&height=768&srs=EPSG%3A3035&format=application/openlayers`

The similar index Tx90p is written correctly with a capital "T" in the geoserver.


For the index **HI_Tx75p***, this is not available in the geoserver - only the index HI_Tx75p-consecutive-max* is there. I see that HI_Tx75p is in the data package, but I cannot check if the data is on the clarity-ftp server, as it is not responding at the moment. So, either the problem is the data has not been uploaded to the clarity-ftp (my problem), or it has not yet been converted to geotiff. I'll update this once I get access to the clarity-ftp.

**Comment by therter** [comment]
> For the index **CI_Tn10p***, I think the problem is that in the geoserver, the index is written with a small "t" instead of with a capital T, i.e. see second line of the long link "....CI_tn10p_...:" :

I will change this

Done. The name of the index CI_Tn10p* uses a capital T now.

**Comment by p-a-s-c-a-l** [comment]
So this is resolved now?

**Comment by RobAndGo** [comment]
I think the only issue remaining was with the **HI_Tx75p_** index. I was able to check on the clarityftp (got the new log-in details just yesterday) and it is not there. I think this is because it was replaced by the **HI_Tx75p-consecutive-max** index. In this case, I think it would be easier if I removed the  **HI_Tx75p_** index from the European-wide dataset.

Update: Hmm, I can't seem to be able to make any changes to the European wide dataset, i.e. there are no buttons to click on which say "edit" or "remove". And I am logged in and viewing the datapackage via the "Maintenance" menu.

**Comment by therter** [comment]
>  I can't seem to be able to make any changes to the European wide dataset, i.e. there are no buttons to click on which say "edit" or "remove". And I am logged in and viewing the datapackage via the "Maintenance" menu.

At the top of the page should be an edit button

![editDp](https://user-images.githubusercontent.com/1788509/85840035-1eef4580-b79c-11ea-87f0-3e3f17645b5f.png)

**Comment by RobAndGo** [comment]
I'm afraid I am one of the "have-nots". ![bawling](https://user-images.githubusercontent.com/45385637/85842177-92468680-b79f-11ea-8804-be495f90d749.gif)
I don't see these menu options. With chrome and firefox it looks like this for me:

![2020-06-26_112129](https://user-images.githubusercontent.com/45385637/85841907-151b1180-b79f-11ea-9d52-be022a952d19.png)

**Comment by p-a-s-c-a-l** [comment]
> I can't seem to be able to make any changes to the European wide dataset,

in which instance? CSIS-DEV?

**Comment by RobAndGo** [comment]
Ok, so that's the problem. I was using the normal CSIS version the whole time. Sorry, my mistake!
Now, with the https://csis-dev.myclimateservice.eu/user/login , it appears that my normal login does not work. Do I need a new account for this developer instance?

**Comment by p-a-s-c-a-l** [comment]
> Do I need a new account for this developer instance?

I've sent you a new password. BTW there's duplicate layer **HI_summer-days_ensstd** in the European Data Package:

> index.js:1 Warning: Encountered two children with the same key, `HI_summer-days_ensstd-347`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

**Comment by RobAndGo** [comment]
Thanks @p-a-s-c-a-l!!! I was able to remove the HI_Tx75p_ Index.
But how did you find the duplicate layer of **HI_summer-day_ensstd**? I thought it would be in the "Heat Index Summer Days" index, but this was not the case. I clicked on other indices, to see if I forgot to remove a duplicate HI_summer-day_ensstd after cloning, but I couldn't find anything. Could you maybe find out in which index this duplicate is in?

I assume you mean the duplicate is in the "service path" links.

**Comment by p-a-s-c-a-l** [comment]
> I assume you mean the duplicate is in the "service path" links.

Yes, I've found the resource with the additional HI_summer-day_ensstd 'reference' aka 'service path' (sorry, our [naming conventions ](https://www.mediawiki.org/wiki/Naming_things) are virtually non-existent) and removed it in the DEV instance.

**Comment by p-a-s-c-a-l** [comment]
> Could not find layer **europe:HI_Tx75p_historical_19710101-20001231_ensmean**
> Could not find layer **europe:HI_Tx75p_historical_19710101-20001231_enstd**

**Comment by p-a-s-c-a-l** [comment]
> Could not find layer europe:PI_snow-days_historical_19710101-20001231_ensstd

**Comment by RobAndGo** [comment]
OK, the snow days was my error.  ![foreheadslap](https://user-images.githubusercontent.com/45385637/86089534-b1e3f480-baa8-11ea-86e0-0dfbca28fa12.gif)

I had incorrectly named it in the clarityftp, which meant that @ghilbrae or @LauraMTG repeated that incorrect name in the geotiffs. 
I will rename the files on the clarityftp, but @ghilbrae or @LauraMTG need to change it on the Meteogrid geoserver. The change is:
**`SnowDays_  -> PI_snow-days_`**

**Comment by p-a-s-c-a-l** [comment]
Has this been resolved now? Do you know more @therter ?

**Comment by p-a-s-c-a-l** [comment]
> Has this been resolved now? Do you know more @therter ?

@therter ?

**Comment by therter** [comment]
The following layers are still missing:
  - europe:PI_snow-days_rcp85_20410101-20701231_ensmean [old link](https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_snow-days_rcp85_20410101-20701231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619), [new link](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_snow-days_rcp85_20410101-20701231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619)
  - europe:PI_snow-days_rcp85_20410101-20701231_ensstd [old link](https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_snow-days_rcp85_20410101-20701231_ensstd&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&tileSize=1536&attribution=&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619),  [new link](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_snow-days_rcp85_20410101-20701231_ensstd&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&tileSize=1536&attribution=&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619) 

and the HI_Tx75p... layers are still in the european data packages ([European DP for basic screening](https://csis-dev.myclimateservice.eu/node/3982), [European Wide Data Package](https://csis-dev.myclimateservice.eu/node/682)):

**Comment by RobAndGo** [comment]
As mentioned above in the post [here](https://github.com/clarity-h2020/data-package/issues/69#issuecomment-651563003), the required correction is a name change of the layers on the Meteogrid server, which, as I understand it, can only be done by METEOGRID (@ghilbrae or @LauraMTG).

**Comment by p-a-s-c-a-l** [comment]
No, on **ATOS** GeoServer. @ghilbrae Can you please disable METEOGRID GeoServer so that nobody will accidentality access the wrong server?

@therter @RobAndGo @DanielRodera 

I couldn't find **any** snow-days layers on [https://geoserver.myclimateservice.eu](https://geoserver.myclimateservice.eu/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.layer.LayerPage) 

❓

**Comment by DanielRodera** [comment]
I cannot find any snow-days layers published in the Geoserver. 

I also take a look at the folder where are stored the original data I couldn't find any snow-days layers neither. 

@ghilbrae could you please a look at it? you know better the structure of this folder and where could be stored these layers,

**Comment by p-a-s-c-a-l** [comment]
> I'll have to look at this in more detail, but I think one of the problems with snow days, was that it was one of the last datasets to be uploaded, and I'm not sure if @ghilbrae or @LauraMTG had time to convert them to geotiff.

**Comment by LauraMTG** [comment]
In effect @p-a-s-c-a-l , the snow day indices have not been processed by MeteoGrid. If such a conversion is needed, that would not be inconvenient for us.
